### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by deanmcpherson** [lelandrichardson/react-native-mapview#1]
Hey @lelandrichardson, Is it possible to get this running from an npm install?

**Comment by christopherdro** [comment]
Yes, I tried it last night. Both iOS and android run but have a few crashes on specific examples.

**Comment by lelandrichardson** [comment]
This repo is not meant to be a consumable module via npm... it is/was mostly a staging area until I get it ready to merge into RN.  I should probably explicitly mention this in the README.

If there is a lot of demand for this component for people that can't wait for 0.19 or won't be able to upgrade, i can probably release this as a standalone as well...

@christopherdro did any examples other than the image example crash?  bug reports welcome :)

**Comment by christopherdro** [comment]
On top of my head it was a issue with `Animate.multiply` complaining that multiply was not a function.

@lelandrichardson So is this slated for 0.19?

**Comment by lelandrichardson** [comment]
Ahh. Gotcha. Yeah - in order to get this app up and running, you will need to expose `AnimatedRegion` in `AnimatedImplementation.js` as well as include the `Animated.multiply` which is in 0.18.  I will put instructions in the readme...

**Comment by deanmcpherson** [comment]
I'll close this as the discussion to turn this into a library has continued in #2
