### ISSUE TITLE
No map displayed

### ISSUE THREAD

**Issue by gendronb** [lelandrichardson/react-native-mapview#3]
Installation and compilation work fine, but nothing is displayed (neither tiles or markers or shapes) on Android

**Comment by lelandrichardson** [comment]
@gendronb hmm. That's a bit worrisome. Are there any errors or console output?

**Comment by gendronb** [comment]
I get 3 warnings : 

1. Native component for "RCTMap" does not exist
2. Native component for "RCTModalHostView" does not exist
3. Native component for "RCTWebView" does not exist

**Comment by lelandrichardson** [comment]
hmm. Those warnings are always there, are they not? They shouldn't have anything to do with this library.

**Comment by gendronb** [comment]
@lelandrichardson : You're probably right about the warning...

Also, it does not work at all on the Android emulator (on Windows).

As I said before, the samples seem to be working OK, but the maps are always blank (no map tiles, no overlays), see attached screenshot.

![screenshot_2016-01-13-12-54-30](https://cloud.githubusercontent.com/assets/1242289/12302809/22a97802-b9f5-11e5-9b1a-49cdc4345f8e.png)

I'm testing on a Samsung S3

**Comment by lelandrichardson** [comment]
This may be API key related?  If it is, we should figure out where we can surface an error that's more helpful.

**Comment by gendronb** [comment]
Yep, you were right,I was missing a valid API key.

Works great now, wow!

Excellent work, thanks @lelandrichardson for your help!

**Comment by lelandrichardson** [comment]
Oh, great! Thanks for getting it figured out. I will add to my list providing a nice redbox screen whenever an API key is missing / invalid.

**Comment by CEOGavin** [comment]
I had the same issue. Thanks for that @lelandrichardson. Worked!

**Comment by BigPun86** [comment]
Hey there. Module works fine with release apk (signed), but when i am using the debug.apk on emulator as well as on real device i don´t see any Map...Any ideas?

Running on Mac / ReactNative 0.20

**Comment by sahiljain112** [comment]
I faced the same problem. I generated a valid key for Android and it worked after that.
Thanks @lelandrichardson
