### ISSUE TITLE
Error: Animated.multiply is not a function

### ISSUE THREAD

**Issue by jetaix** [lelandrichardson/react-native-mapview#8]
First off, nice work and MERCI! 

When I run 'Animating with MapViews' exemple on iOS (Simulator) I get this error ->"Animated.multiply is not a function. (In 'Animated.multiply(isIndex,panY)', 'Animated.multiply' is undefined)"

Ideas ?

**Comment by christopherdro** [comment]
@jetaix See https://github.com/lelandrichardson/react-native-mapview/issues/2#issuecomment-171454862
